language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install

before_script:
  - npm install -g hexo-cli  
  - npm install --save hexo-deployer-git
 # - npm install -g gulp

script:
  - git submodule init      # 用于更新主题
  - git submodule update
  - hexo g

after_script:
  - git config --global user.name "Your Name"
  - git config --global user.email "Your Email"
  - sed -i'' "/^ *repo/s~github\.com~${GH_TOKEN}@github.com~" _config.yml
  - hexo deploy
# E: Build LifeCycle

branches:
  only:
    - master
